stages:
  split_data:
    cmd: python src/split_data.py
    deps:
    - src/split_data.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize_data:
    cmd: python src/normalize_data.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/normalize_data.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  grid_search:
    cmd: python src/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/grid_search.py
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/train_model.py
    outs:
    - models/trained_model.pkl
  evaluate_model:
    cmd: python src/evaluate_model.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/trained_model.pkl
    - src/evaluate_model.py
    outs:
    - data/processed/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
