stages:
  normalize_data:
    cmd: python src/normalize_data.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/normalize_data.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  grid_search:
    cmd: python src/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/grid_search.py
    outs:
    - models/best_params.pkl
